# -*- coding: utf-8 -*-
"""datawrangling_Eti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16y4yVAcaXWOu3pZnBYMgLoeGLXqM5m7_
"""

import pandas as pd
import numpy as np
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

# check for null values
df.isnull().sum()/df.count()*100

df.dtypes

"""## TASK 1: Calculate the number of launches on each site"""

df['LaunchSite'].value_counts()

"""## TASK 2: Calculate the number and occurrence of each orbit"""

df['Orbit'].value_counts()

"""## TASK 3: Calculate the number and occurence of mission outcome per orbit type"""

landing_outcomes = df['Outcome'].value_counts()
landing_outcomes

for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])
bad_outcomes

"""## TASK 4: Create a landing outcome label from Outcome column"""

landing_class = []

for key, value in df['Outcome'].items():
    if value in bad_outcomes:
        landing_class.append(0)
    else:
        landing_class.append(1)

df['Class']=landing_class
df[['Class']].head(8)

df.head(5)

df["Class"].mean()

# export the data
df.to_csv("dataset_part_2.csv", index=False)
df.to_csv("dataset_part_2.csv", index=False)